### ISSUE TITLE
Remove dashes from docker folders

### ISSUE THREAD

**Issue by lfpino** [EngFlow/example#24]
This repo has two folderers that start with "docker-" but having dashes in the names is sometimes problematic. We should use Camelcase instead.

**Comment by Yannic** [comment]
camelCase is problematic as well because case-insensitive filesystems. Let's make it `snake_case`.

Also, I can't think of a case where dashes are problematic tbh.

**Comment by lfpino** [comment]
You're right, underscore xD, the dashes were problematic for the package name in Java IIRC.

I created this as a very simple good first issue :-)
